/*
DROP TABLE "MEMBER" CASCADE CONSTRAINTS;
DROP TABLE "ROOM" CASCADE CONSTRAINTS;
DROP TABLE "PRODUCT_TABLE" CASCADE CONSTRAINTS;
DROP TABLE "COUPON" CASCADE CONSTRAINTS;
DROP TABLE "RESERVATION" CASCADE CONSTRAINTS;
DROP TABLE "CATEGORY" CASCADE CONSTRAINTS;
DROP TABLE "QNA" CASCADE CONSTRAINTS;
DROP TABLE "FAQ" CASCADE CONSTRAINTS;
DROP TABLE "NOTICE" CASCADE CONSTRAINTS;
DROP TABLE "FAQ_BOARD" CASCADE CONSTRAINTS;
DROP TABLE "PRODUCT" CASCADE CONSTRAINTS;
DROP TABLE "QNA_BOARD" CASCADE CONSTRAINTS;


DROP SEQUENCE SEQ_MNO;
DROP SEQUENCE SEQ_RNO;
DROP SEQUENCE SEQ_PRNO;
DROP SEQUENCE SEQ_BNO;
DROP SEQUENCE SEQ_NNO;
DROP SEQUENCE SEQ_CNO;
DROP SEQUENCE SEQ_RENO;
DROP SEQUENCE FAQ_SEQ;
DROP SEQUENCE QNA_BOARD_SEQ;
DROP SEQUENCE SEQ_FNO;
*/

/*각 테이블의 생성문과 코멘트*/

CREATE TABLE "MEMBER" (
                          "MEMBER_NO"        NUMBER             	 		        NOT NULL,
                          "MEMBER_ID"        VARCHAR2(100)      	 		        NOT NULL,
                          "MEMBER_PWD"       VARCHAR2(100)      		 		    NOT NULL,
                          "MEMBER_NAME"      VARCHAR2(100)      		 		    NOT NULL,
                          "MEMBER_PHONE"     VARCHAR2(100)      			 		    NULL,
                          "MEMBER_DATE"      DATE DEFAULT SYSDATE            	    NOT NULL,
                          "ADMIN_CHECK"      VARCHAR2(20)       DEFAULT 'N'         NOT NULL,
                          "RECOM_COUNT"      NUMBER             DEFAULT 0           NOT NULL,
                          "MEMBER_STATUS"    VARCHAR2(20)       DEFAULT 'Y'   	        NULL,
                          "AD_AGREE"         VARCHAR2(20)       DEFAULT 'N'   	        NULL,
                          "RECOM_CODE"       VARCHAR2(20)      				        NOT NULL,
                          "MEMBER_POINT"     NUMBER                   				    NULL,
                          "TOKEN1"           VARCHAR2(1000)      					    NULL,
                          "TOKEN2"           VARCHAR2(1000)      					    NULL
);

COMMENT ON COLUMN "MEMBER"."MEMBER_NO" IS       '회원식별자';
COMMENT ON COLUMN "MEMBER"."MEMBER_NAME" IS     '이름';
COMMENT ON COLUMN "MEMBER"."MEMBER_ID" IS       '아이디';
COMMENT ON COLUMN "MEMBER"."MEMBER_PWD" IS      '비밀번호';
COMMENT ON COLUMN "MEMBER"."MEMBER_PHONE" IS    '연락처';
COMMENT ON COLUMN "MEMBER"."ADMIN_CHECK" IS     'N.일반유저  A관리자';
COMMENT ON COLUMN "MEMBER"."RECOM_COUNT" IS     '추천받은 횟수';
COMMENT ON COLUMN "MEMBER"."MEMBER_STATUS" IS   'B 블라인드 N일반 D 삭제된계정';
COMMENT ON COLUMN "MEMBER"."AD_AGREE" IS        'Y 는 동의 N은 비동의';

CREATE TABLE "ROOM" (
                        "ROOM_NO"               NUMBER      					NOT NULL,
                        "ROOM_NAME"             VARCHAR2(100)      		        NOT NULL,
                        "ROOM_TYPE"             VARCHAR2(255)      				    NULL,
                        "ROOM_CAPACITYMIN"      NUMBER      			        NOT NULL,
                        "ROOM_CAPACITYMAX"      NUMBER      			        NOT NULL,
                        "ROOM_INFORMATION"      VARCHAR2(300)                   NOT NULL,
                        "ROOM_FILEPATH"         VARCHAR2(1000)      		        NULL
);

COMMENT ON COLUMN "ROOM"."ROOM_NO" IS           '룸테이블 식별자';
COMMENT ON COLUMN "ROOM"."ROOM_NAME" IS         '룸명';
COMMENT ON COLUMN "ROOM"."ROOM_CAPACITYMIN" IS     '수용인원최소';
COMMENT ON COLUMN "ROOM"."ROOM_CAPACITYMAX" IS     '수용인원최대';
COMMENT ON COLUMN "ROOM"."ROOM_FILEPATH" IS     '사진저장경로';

CREATE TABLE "PRODUCT_TABLE" (
                                 "PRODUCT_NO"         NUMBER     			      NOT NULL,
                                 "ROOM_NO"            NUMBER      			      NOT NULL,
                                 "ROOM_TIME"          DATE   					      NULL,
                                 "ROOM_CONDITION"     VARCHAR2(10)      	      NOT NULL,
                                 "ROOM_PRICE"         NUMBER      			      NOT NULL,
                                 "ROOM_INFO"          VARCHAR2(500)      		      NULL,
                                 "RESERVATION_DATE"   DATE         			      NOT NULL,
                                 "PAYMENT_DATE"       DATE       				      NULL
);

COMMENT ON COLUMN "PRODUCT_TABLE"."PRODUCT_NO" IS        '상품식별자';
COMMENT ON COLUMN "PRODUCT_TABLE"."ROOM_NO" IS           '룸테이블 식별자';
COMMENT ON COLUMN "PRODUCT_TABLE"."ROOM_CONDITION" IS    'Y 이용가능. O이용중 R수리중';
COMMENT ON COLUMN "PRODUCT_TABLE"."ROOM_PRICE" IS        '상품가격';
COMMENT ON COLUMN "PRODUCT_TABLE"."ROOM_INFO" IS         '시설정보';
COMMENT ON COLUMN "PRODUCT_TABLE"."RESERVATION_DATE" IS  '예약하는날';
COMMENT ON COLUMN "PRODUCT_TABLE"."PAYMENT_DATE" IS      '결제 한 날';

CREATE TABLE "QNA" (
                       "BOARD_NO"         NUMBER                      NOT NULL,
                       "MEMBER_NO"        NUMBER                      NOT NULL,
                       "CATEGORY"         VARCHAR2(200)               NOT NULL,
                       "BOARD_TITLE"      VARCHAR2(200)               NOT NULL,
                       "BOARD_CONTENT"    VARCHAR2(4000)              NOT NULL,
                       "BOARD_COUNT"      NUMBER                          NULL,
                       "BOARD_ANSWER"     VARCHAR2(20)   DEFAULT 'N'  NOT NULL,
                       "BOARD_CONDITION"  VARCHAR2(20)                    NULL,
                       "BOARD_DATE"       DATE DEFAULT SYSDATE        NOT NULL,
                       "ANSWER_CONTENT"   VARCHAR2(200)                   NULL,
                       "MEMBER_NAME"      VARCHAR2(100)               NOT NULL
);

COMMENT ON COLUMN "QNA"."BOARD_NO" IS           '게시판 식별자';
COMMENT ON COLUMN "QNA"."MEMBER_NO" IS          '회원식별자';
COMMENT ON COLUMN "QNA"."CATEGORY" IS           '카테고리';
COMMENT ON COLUMN "QNA"."BOARD_TITLE" IS        '제목';
COMMENT ON COLUMN "QNA"."BOARD_CONTENT" IS      '내용';
COMMENT ON COLUMN "QNA"."BOARD_COUNT" IS        '조회수';
COMMENT ON COLUMN "QNA"."BOARD_ANSWER" IS       '답변시 Y 아니면 N';
COMMENT ON COLUMN "QNA"."BOARD_CONDITION" IS    'B 블라인드 Y일반 D 삭제된글';
COMMENT ON COLUMN "QNA"."BOARD_DATE" IS         '작성일';
COMMENT ON COLUMN "QNA"."ANSWER_CONTENT" IS     '답변내용';
COMMENT ON COLUMN "QNA"."MEMBER_NAME" IS        '작성자';

CREATE TABLE "FAQ" (
                       "BOARD_NO"         NUMBER                        NOT NULL,
                       "MEMBER_NO"        NUMBER                        NOT NULL,
                       "CATEGORY"         VARCHAR2(150)                 NOT NULL,
                       "BOARD_TITLE"      VARCHAR2(200)                 NOT NULL,
                       "BOARD_CONTENT"    VARCHAR2(4000)                NOT NULL,
                       "BOARD_COUNT"      NUMBER                            NULL,
                       "BOARD_ANSWER"     VARCHAR2(20)   DEFAULT 'N'    NOT NULL,
                       "BOARD_CONDITION"  VARCHAR2(20)                      NULL,
                       "BOARD_DATE"  DATE DEFAULT SYSDATE               NOT NULL
);

COMMENT ON COLUMN "FAQ"."BOARD_NO" IS           '게시판 식별자';
COMMENT ON COLUMN "FAQ"."MEMBER_NO" IS          '회원식별자';
COMMENT ON COLUMN "FAQ"."BOARD_TITLE" IS        '제목';
COMMENT ON COLUMN "FAQ"."BOARD_CONTENT" IS      '내용';
COMMENT ON COLUMN "FAQ"."BOARD_COUNT" IS        '조회수';
COMMENT ON COLUMN "FAQ"."BOARD_ANSWER" IS       '답변시 Y 아니면 N';
COMMENT ON COLUMN "FAQ"."BOARD_CONDITION" IS    'B 블라인드 Y일반 D 삭제된글';
COMMENT ON COLUMN "FAQ"."BOARD_DATE" IS         '작성일';

CREATE TABLE "CATEGORY" (
                            "CATEGORY"          VARCHAR2(200)      NOT NULL,
                            "CATEGORY_NAME"     VARCHAR2(200)      NOT NULL
);

CREATE TABLE "NOTICE" (
                          "NOTICE_NO"           NUMBER                        NOT NULL,
                          "MEMBER_NO"           NUMBER                        NOT NULL,
                          "NOTICE_TITLE"        VARCHAR2(200)                 NOT NULL,
                          "NOTICE_CONTENT"      VARCHAR2(4000)                NOT NULL,
                          "NOTICE_CONDITION"    VARCHAR2(20)   DEFAULT 'Y'        NULL
);

COMMENT ON COLUMN "NOTICE"."NOTICE_NO" IS          '공지사항 식별자';
COMMENT ON COLUMN "NOTICE"."MEMBER_NO" IS          '회원식별자';
COMMENT ON COLUMN "NOTICE"."NOTICE_TITLE" IS       '공지사항 제목';
COMMENT ON COLUMN "NOTICE"."NOTICE_CONTENT" IS     '공지사항 내용';
COMMENT ON COLUMN "NOTICE"."NOTICE_CONDITION" IS   'B 블라인드 N일반 D 삭제된글';

CREATE TABLE "COUPON" (
                          "COUPON_NO"              NUMBER                              NOT NULL,
                          "MEMBER_NO"              NUMBER                              NOT NULL,
                          "COUPON_NAME"            VARCHAR2(1000)                          NULL,
                          "COUPON_VALID"           VARCHAR2(20)      DEFAULT 'N'       NOT NULL,
                          "COUPON_PRICE"           NUMBER                              NOT NULL,
                          "COUPON_DATE"            DATE                                NOT NULL,
                          "COUPON_CODE"            VARCHAR2(40)                        NOT NULL
);

COMMENT ON COLUMN "COUPON"."COUPON_NO" IS          '가용쿠폰식별자';
COMMENT ON COLUMN "COUPON"."MEMBER_NO" IS          '회원식별자';
COMMENT ON COLUMN "COUPON"."COUPON_NAME" IS        '쿠폰이름';
COMMENT ON COLUMN "COUPON"."COUPON_VALID" IS       'Y는 사용됨 N 은  아직';
COMMENT ON COLUMN "COUPON"."COUPON_PRICE" IS       '1000원 또는 3000원';
COMMENT ON COLUMN "COUPON"."COUPON_DATE" IS        'SYSDATE 기준 한달  = SYSDATE + 30';
COMMENT ON COLUMN "COUPON"."COUPON_CODE" IS        '앞에 영어 4글자 후 숫자 4글자';

CREATE TABLE "RESERVATION" (
                               "RESERVATION_NO"          NUMBER                       NOT NULL,
                               "MEMBER_NO"               NUMBER                       NOT NULL,
                               "PRODUCT_NO"              NUMBER                       NOT NULL,
                               "RESERVATION_NAME"        VARCHAR2(100)                NOT NULL,
                               "RESERVATION_EMAIL"       VARCHAR2(255)                    NULL,
                               "RESERVATION_PHONE"       VARCHAR2(100)                    NULL,
                               "RESERVATION_PERSONNEL"   NUMBER                       NOT NULL,
                               "RESERVATION_DATE"        DATE                         NOT NULL,
                               "RESERVATION_TIME"        VARCHAR2(255)                    NULL,
                               "PAYMENT_METHOD"          VARCHAR2(255)                    NULL,
                               "PAYMENT_DATE"            DATE                         NOT NULL,
                               "PAYMENT_PRICE"           NUMBER                       NOT NULL,
                               "RESERVATION_CONDITION"   VARCHAR2(20)   DEFAULT 'Y'   NOT NULL,
                               "PAYMENT_INFO"            VARCHAR2(20)                     NULL
);


/*7개의 테이블 시퀀스 */

CREATE SEQUENCE SEQ_MNO /*member SEQUENCE*/
    MINVALUE 1
    MAXVALUE 999999999999
    START WITH 1
    INCREMENT BY 1
    NOCYCLE;
CREATE SEQUENCE SEQ_RNO /*ROOM SEQUENCE*/
    MINVALUE 1
    MAXVALUE 999999999999
    START WITH 1
    INCREMENT BY 1
    NOCYCLE;
CREATE SEQUENCE SEQ_PRNO /*product SEQUENCE*/
    MINVALUE 1
    MAXVALUE 999999999999
    START WITH 1
    INCREMENT BY 1
    NOCYCLE;
CREATE SEQUENCE SEQ_BNO /*BOARD SEQUENCE*/
    MINVALUE 1
    MAXVALUE 999999999999
    START WITH 1
    INCREMENT BY 1
    NOCYCLE;
CREATE SEQUENCE SEQ_NNO /*NOTICE SEQUENCE*/
    MINVALUE 1
    MAXVALUE 999999999999
    START WITH 1
    INCREMENT BY 1
    NOCYCLE;
CREATE SEQUENCE SEQ_CNO /*coupon SEQUENCE*/
    MINVALUE 1
    MAXVALUE 999999999999
    START WITH 1
    INCREMENT BY 1
    NOCYCLE;

CREATE SEQUENCE SEQ_RENO /*reservation SEQUENCE*/
    MINVALUE 1
    MAXVALUE 999999999999
    START WITH 1
    INCREMENT BY 1
    NOCYCLE;

/*PK 적용조건*/

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY ("MEMBER_NO");
ALTER TABLE "ROOM" ADD CONSTRAINT "PK_ROOM" PRIMARY KEY ("ROOM_NO");
ALTER TABLE "PRODUCT_TABLE" ADD CONSTRAINT "PK_PRODUCT_TABLE" PRIMARY KEY ("PRODUCT_NO");
ALTER TABLE "QNA" ADD CONSTRAINT "PK_QNA" PRIMARY KEY ("BOARD_NO");
ALTER TABLE "FAQ" ADD CONSTRAINT "PK_FAQ" PRIMARY KEY ("BOARD_NO");
ALTER TABLE "CATEGORY" ADD CONSTRAINT "PK_CATEGORY" PRIMARY KEY ("CATEGORY");
ALTER TABLE "NOTICE" ADD CONSTRAINT "PK_NOTICE" PRIMARY KEY ("NOTICE_NO");
ALTER TABLE "COUPON" ADD CONSTRAINT "PK_COUPON" PRIMARY KEY ("COUPON_NO");
ALTER TABLE "RESERVATION" ADD CONSTRAINT "PK_RESERVATION" PRIMARY KEY ("RESERVATION_NO");



/* FK 적용 조건*/

ALTER TABLE "PRODUCT_TABLE" ADD CONSTRAINT "FK_ROOM_TO_PRODUCT" FOREIGN KEY ("ROOM_NO") REFERENCES "ROOM" ("ROOM_NO")               ON DELETE CASCADE ;
ALTER TABLE "QNA" ADD CONSTRAINT "FK_MEMBER_TO_QnA" FOREIGN KEY ("MEMBER_NO")REFERENCES "MEMBER" ("MEMBER_NO")                      ON DELETE CASCADE ;
ALTER TABLE "QNA" ADD CONSTRAINT "FK_CATEGORY_TO_QnA" FOREIGN KEY ("CATEGORY")REFERENCES "CATEGORY" ("CATEGORY")                    ON DELETE CASCADE ;
ALTER TABLE "FAQ" ADD CONSTRAINT "FK_MEMBER_TO_FAQ" FOREIGN KEY ("MEMBER_NO")REFERENCES "MEMBER" ("MEMBER_NO")                      ON DELETE CASCADE ;
ALTER TABLE "FAQ" ADD CONSTRAINT "FK_CATEGORY_TO_FAQ" FOREIGN KEY ("CATEGORY")REFERENCES "CATEGORY" ("CATEGORY")                    ON DELETE CASCADE ;
ALTER TABLE "NOTICE" ADD CONSTRAINT "FK_MEMBER_TO_NOTICE" FOREIGN KEY ("MEMBER_NO")REFERENCES "MEMBER" ("MEMBER_NO")                ON DELETE CASCADE ;
ALTER TABLE "COUPON" ADD CONSTRAINT "FK_MEMBER_TO_COUPON" FOREIGN KEY ("MEMBER_NO") REFERENCES "MEMBER" ("MEMBER_NO")               ON DELETE CASCADE ;
ALTER TABLE "RESERVATION" ADD CONSTRAINT "FK_MEMBER_TO_RE" FOREIGN KEY ("MEMBER_NO") REFERENCES "MEMBER" ( "MEMBER_NO")             ON DELETE CASCADE ;
ALTER TABLE "RESERVATION" ADD CONSTRAINT "FK_PRODUCT_TO_RE" FOREIGN KEY ( "PRODUCT_NO") REFERENCES "PRODUCT_TABLE" ( "PRODUCT_NO")  ON DELETE CASCADE ;


/* 12/29 민진 주영 게시판 DB테이블 수정*/

/* 12/29일 NOTICE 테이블 수정: 1. 조회수 추가, 2. 글상태 삭제 */
ALTER TABLE NOTICE ADD NOTICE_COUNT NUMBER DEFAULT 0; 
ALTER TABLE NOTICE DROP COLUMN NOTICE_CONDITION;

/* 12/29일 FAQ 테이블 수정: 1. 조회수 삭제, 2. 글상태 삭제 */
ALTER TABLE FAQ DROP COLUMN BOARD_CONDITION;
ALTER TABLE FAQ DROP COLUMN BOARD_COUNT;

/* 12/29일 QNA 테이블 수정: 1. 조회수 삭제, 2. 글상태 삭제 */
ALTER TABLE QNA DROP COLUMN BOARD_COUNT;
ALTER TABLE QNA DROP COLUMN BOARD_CONDITION;

COMMIT;

/* 1/1 NOTICE 테이블 수정: 1. 등록일자 추가 */
ALTER TABLE NOTICE ADD REGDATE TIMESTAMP; 

COMMIT;

/* 1/2 예약관련 테이블 수정*/

ALTER TABLE "PRODUCT_TABLE" DROP COLUMN "RESERVATION_DATE";
ALTER TABLE "PRODUCT_TABLE" DROP COLUMN "PAYMENT_DATE";
ALTER TABLE "PRODUCT_TABLE" DROP COLUMN "ROOM_PRICE";
ALTER TABLE "PRODUCT_TABLE" DROP COLUMN "ROOM_INFO";
ALTER TABLE "PRODUCT_TABLE" DROP COLUMN "ROOM_TIME";
ALTER TABLE "PRODUCT_TABLE" DROP COLUMN "ROOM_CONDITION";

ALTER TABLE "PRODUCT_TABLE" ADD "PRODUCT_DATA"          NUMBER       NOT NULL;
ALTER TABLE "PRODUCT_TABLE" ADD "PRODUCT_CONDITION"     VARCHAR2(10) NOT NULL;

ALTER TABLE "RESERVATION" ADD "RESERVATION_MONITOR"     VARCHAR2(10) NOT NULL;
ALTER TABLE "RESERVATION" ADD "RESERVATION_COMPUTER"    NUMBER       NOT NULL;
ALTER TABLE "RESERVATION" ADD "RESERVATION_PROJECTOR"   NUMBER       NOT NULL;

ALTER TABLE "ROOM" ADD "ROOM_PRICE"                     NUMBER       NOT NULL;

COMMIT;



/* 1/2일 FAQ 테이블 수정: 1. 대답여부삭제 2. 카테고리삭제 */

ALTER TABLE FAQ DROP COLUMN BOARD_ANSWER;
ALTER TABLE FAQ DROP COLUMN CATEGORY;

COMMIT;
-- 컬럼명 변경 --

ALTER TABLE FAQ RENAME COLUMN BOARD_NO      TO FAQ_NO;
ALTER TABLE FAQ RENAME COLUMN BOARD_TITLE   TO FAQ_TITLE;
ALTER TABLE FAQ RENAME COLUMN BOARD_CONTENT TO FAQ_CONTENT;
ALTER TABLE FAQ RENAME COLUMN BOARD_DATE    TO FAQ_DATE; 

COMMIT;
-- FQA 시퀀스 추가 --
CREATE SEQUENCE SEQ_FNO /*FAQ SEQUENCE*/
    MINVALUE 1
    MAXVALUE 999999999999
    START WITH 1
    INCREMENT BY 1
    NOCYCLE;

/* 1/2일 QNA 테이블 수정: 1. 카테고리삭제 */

ALTER TABLE QNA DROP COLUMN CATEGORY;

COMMIT;



/* 1/4일 QNA 테이블 마지막 수정 */

/* QNA_BOARD 테이블 생성 */
CREATE TABLE QNA_BOARD(
QNA_NO NUMBER PRIMARY KEY,
QNA_WRITER VARCHAR2(200) NOT NULL,
QNA_TITLE VARCHAR2(200) NOT NULL,
QNA_CONTENT VARCHAR2(4000) NOT NULL,
QNA_DATE DATE,
ANSWER_TITLE VARCHAR2(200),
ANSWER_CONTENT VARCHAR2(200),
BOARD_ANSWER NUMBER,
PAGING_STACK NUMBER
);

/* QNA_BOARD_SEQ 시퀀스 생성 */
CREATE SEQUENCE QNA_BOARD_SEQ
    MINVALUE 1
    MAXVALUE 999999999999
    START WITH 1
    INCREMENT BY 1
    NOCYCLE;

/* QNA테이블과 SEQ_BNO 삭제 */
DROP TABLE QNA;
DROP SEQUENCE SEQ_BNO;

COMMIT;


/* 1/5일 FAQ 테이블 마지막 수정 */

/* FAQ_BOARD 테이블 생성 */
CREATE TABLE FAQ_BOARD (
    FAQ_NO NUMBER PRIMARY KEY,
    MEMBER_NO NUMBER NOT NULL,
    FAQ_TITLE VARCHAR2(100) NOT NULL,
    FAQ_CONTENT VARCHAR2(2000)  NOT NULL,
    FAQ_DATE DATE
);

/* FAQ_SEQ 시퀀스 생성 */
CREATE SEQUENCE FAQ_SEQ
    MINVALUE 1
    MAXVALUE 999999999999
    START WITH 1
    INCREMENT BY 1
    NOCYCLE;
    
/* FAQ 테이블 삭제 */
DROP TABLE FAQ;

COMMIT;

/* 1/7일 MEMBER 테이블 컬럼 수정 */
/* not null에서 null로 변경 해줌 */
ALTER TABLE "MEMBER" DROP COLUMN "RECOM_CODE";
ALTER TABLE "MEMBER" ADD "RECOM_CODE" VARCHAR2(20) NULL;
COMMIT;

/* PRODUCT_TABLE테이블 PRODUCT로 변경*/
ALTER TABLE "PRODUCT_TABLE" RENAME TO "PRODUCT";
COMMIT;

/* 1/8일 MEMBER 테이블 */
ALTER TABLE "MEMBER" MODIFY MEMBER_STATUS DEFAULT 'N';
COMMIT;

/* 1/9일 QNA_BOARD 테이블 카테고리 추가띵~ */
ALTER TABLE QNA_BOARD ADD CATEGORY VARCHAR2(200);
COMMIT;

/* 1/9 상품테이블 O가 예약 X가 취소 디폴트생성값 O*/
ALTER TABLE "PRODUCT" MODIFY PRODUCT_CONDITION DEFAULT 'O';
COMMIT;
